export = {
  PORT: 5000,
  DISCORD_TOKEN: 'NTY5OTAyNDM2NTQ2NzcyOTky.XuQ4KA.mDmmWeMNjxDngifkZEJUfabPuZ0',
  PREFIX: '/dys',
};

//   export TOKEN=NTY5OTAyNDM2NTQ2NzcyOTky.XL3ZtA.iPA3xg2KMdkYepH4ReNGKP963lA
//   export PREFIX=-
//   export GOOGLE_API_KEY=AIzaSyBvAPWUe_7uLR-X89bknKEENLT1kdaMYI
